//! Handle types for query results, source access, and subscriptions.

use std::marker::PhantomData;
use std::sync::Arc;
use std::time::Duration;

use arrow::array::RecordBatch;
use arrow::datatypes::SchemaRef;

use laminar_core::streaming::{Record, Subscription};

use crate::catalog::{ArrowRecord, SourceEntry};
use crate::DbError;

/// Result of executing a SQL statement.
#[derive(Debug)]
pub enum ExecuteResult {
    /// DDL statement completed (CREATE, DROP, ALTER).
    Ddl(DdlInfo),
    /// Query is running, subscribe to results.
    Query(QueryHandle),
    /// Rows were affected (INSERT INTO).
    RowsAffected(u64),
    /// Metadata result (SHOW, DESCRIBE).
    Metadata(RecordBatch),
}

impl ExecuteResult {
    /// Convert to `QueryHandle`, or error if this is not a query result.
    ///
    /// # Errors
    /// Returns `DbError::InvalidOperation` if result is not a query.
    pub fn into_query(self) -> Result<QueryHandle, DbError> {
        match self {
            Self::Query(q) => Ok(q),
            _ => Err(DbError::InvalidOperation(
                "Expected a query result".to_string(),
            )),
        }
    }
}

/// Information about a completed DDL statement.
#[derive(Debug, Clone)]
pub struct DdlInfo {
    /// e.g. `"CREATE SOURCE"`.
    pub statement_type: String,
    /// Object affected.
    pub object_name: String,
    /// Whether this statement changed catalog/runtime state. `IF NOT EXISTS`
    /// success uses `false` so the attempted definition cannot replace durable DDL.
    pub(crate) applied: bool,
}

/// Handle to a running streaming query.
#[derive(Debug)]
pub struct QueryHandle {
    pub(crate) id: u64,
    pub(crate) schema: SchemaRef,
    pub(crate) sql: String,
    pub(crate) subscription: Option<Subscription<ArrowRecord>>,
    pub(crate) active: bool,
    pub(crate) cancel_token: tokio_util::sync::CancellationToken,
}

impl QueryHandle {
    /// Output schema.
    #[must_use]
    pub fn schema(&self) -> &SchemaRef {
        &self.schema
    }

    /// SQL text.
    #[must_use]
    pub fn sql(&self) -> &str {
        &self.sql
    }

    /// Query ID.
    #[must_use]
    pub fn id(&self) -> u64 {
        self.id
    }

    /// Whether the query is still active.
    #[must_use]
    pub fn is_active(&self) -> bool {
        self.active
    }

    /// Take the raw `RecordBatch` subscription for this query.
    ///
    /// The subscription is consumed on first call; subsequent calls error.
    ///
    /// # Errors
    /// Returns `DbError::InvalidOperation` if the subscription was already consumed.
    pub fn subscribe_raw(&mut self) -> Result<Subscription<ArrowRecord>, DbError> {
        self.subscription
            .take()
            .ok_or_else(|| DbError::InvalidOperation("Subscription already consumed".to_string()))
    }

    /// Cancel the query and drop its subscription.
    pub fn cancel(&mut self) {
        self.active = false;
        self.subscription = None;
        self.cancel_token.cancel();
    }
}

impl Drop for QueryHandle {
    fn drop(&mut self) {
        self.cancel_token.cancel();
    }
}

/// Deserialize rows from a `RecordBatch`. Auto-generated by `#[derive(FromRecordBatch)]`.
pub trait FromBatch: Sized {
    /// Single row.
    fn from_batch(batch: &RecordBatch, row: usize) -> Self;
    /// All rows.
    fn from_batch_all(batch: &RecordBatch) -> Vec<Self>;
}

/// A typed frame from a named subscription.
#[derive(Debug)]
pub enum TypedSubscriptionFrame<T> {
    /// Rows emitted by one processing cycle.
    Rows {
        /// Deserialized rows in the shared-log entry.
        rows: Vec<T>,
        /// Portal-local delivery sequence; not a durable or cluster-wide resume position.
        sequence: u64,
    },
    /// Durable progress frontier for this checkpoint.
    Barrier {
        /// Portal-local delivery sequence; not a cluster-wide ordering position.
        sequence: u64,
        /// Engine checkpoint epoch.
        epoch: u64,
        /// Engine checkpoint identifier.
        checkpoint_id: u64,
        /// Local-log cut, or a gateway-local compatibility cut in cluster mode.
        through_sequence: u64,
    },
}

/// Typed compatibility frame plus optional durable cluster partition metadata.
#[derive(Debug)]
pub struct TypedSubscriptionEnvelope<T> {
    /// Existing typed rows or checkpoint progress.
    pub frame: TypedSubscriptionFrame<T>,
    /// Present for committed cluster data and progress frames.
    pub cluster: Option<crate::subscription::ClusterSubscriptionFrameMetadata>,
}

/// Terminal failure from a named subscription.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum SubscriptionError {
    /// The consumer fell behind the bounded shared log.
    #[error("subscription fell behind by {skipped} entries")]
    Lagged {
        /// Number of entries no longer available.
        skipped: u64,
    },
    /// The subscribed object or its delivery path failed.
    #[error("subscription failed: {message}")]
    Failed {
        /// Failure detail.
        message: String,
    },
}

/// Typed subscription that deserializes named-stream `RecordBatch` rows.
pub struct TypedSubscription<T: FromBatch> {
    portal: crate::subscription::SubscriptionPortal,
    _phantom: PhantomData<T>,
}

impl<T: FromBatch> TypedSubscription<T> {
    pub(crate) fn new(portal: crate::subscription::SubscriptionPortal) -> Self {
        Self {
            portal,
            _phantom: PhantomData,
        }
    }

    /// Schema resolved while the portal was attached under the topology lock.
    #[must_use]
    pub fn schema(&self) -> SchemaRef {
        self.portal.schema()
    }

    /// Wait for the next data or checkpoint frame.
    ///
    /// # Errors
    /// Returns a terminal error if delivery has a gap or the object fails.
    pub async fn next_frame(
        &mut self,
    ) -> Result<Option<TypedSubscriptionFrame<T>>, SubscriptionError> {
        Ok(self.next_envelope().await?.map(|envelope| envelope.frame))
    }

    /// Wait for the next frame with optional durable cluster partition metadata.
    ///
    /// # Errors
    /// Returns a terminal error if delivery has a gap or the object fails.
    pub async fn next_envelope(
        &mut self,
    ) -> Result<Option<TypedSubscriptionEnvelope<T>>, SubscriptionError> {
        let Some(envelope) = self.portal.next_envelope().await else {
            return Ok(None);
        };
        Ok(Some(TypedSubscriptionEnvelope {
            frame: convert_typed_frame(envelope.frame)?,
            cluster: envelope.cluster,
        }))
    }

    /// Return the next immediately available data or checkpoint frame.
    ///
    /// # Errors
    /// Returns a terminal error if delivery has a gap or the object fails.
    pub fn try_next_frame(
        &mut self,
    ) -> Result<Option<TypedSubscriptionFrame<T>>, SubscriptionError> {
        Ok(self.try_next_envelope()?.map(|envelope| envelope.frame))
    }

    /// Return the next immediately available frame and optional cluster metadata.
    ///
    /// # Errors
    /// Returns a terminal error if delivery has a gap or the object fails.
    pub fn try_next_envelope(
        &mut self,
    ) -> Result<Option<TypedSubscriptionEnvelope<T>>, SubscriptionError> {
        let Some(envelope) = self.portal.try_next_envelope() else {
            return Ok(None);
        };
        Ok(Some(TypedSubscriptionEnvelope {
            frame: convert_typed_frame(envelope.frame)?,
            cluster: envelope.cluster,
        }))
    }

    /// Return the next immediately available row batch, skipping checkpoint markers.
    ///
    /// # Errors
    /// Returns a terminal error if delivery has a gap or the object fails.
    pub fn poll(&mut self) -> Result<Option<Vec<T>>, SubscriptionError> {
        loop {
            match self.try_next_frame()? {
                Some(TypedSubscriptionFrame::Rows { rows, .. }) => return Ok(Some(rows)),
                Some(TypedSubscriptionFrame::Barrier { .. }) => {}
                None => return Ok(None),
            }
        }
    }
}

fn convert_typed_frame<T: FromBatch>(
    frame: crate::subscription::PortalFrame,
) -> Result<TypedSubscriptionFrame<T>, SubscriptionError> {
    match frame {
        crate::subscription::PortalFrame::Batch {
            batch,
            sequence,
            lease: _lease,
        } => Ok(TypedSubscriptionFrame::Rows {
            rows: T::from_batch_all(&batch),
            sequence,
        }),
        crate::subscription::PortalFrame::Barrier {
            sequence,
            epoch,
            checkpoint_id,
            through_sequence,
        } => Ok(TypedSubscriptionFrame::Barrier {
            sequence,
            epoch,
            checkpoint_id,
            through_sequence,
        }),
        crate::subscription::PortalFrame::Lagged(skipped) => {
            Err(SubscriptionError::Lagged { skipped })
        }
        crate::subscription::PortalFrame::Error { message } => {
            Err(SubscriptionError::Failed { message })
        }
    }
}

impl<T: FromBatch> std::fmt::Debug for TypedSubscription<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TypedSubscription")
            .field("portal", &self.portal)
            .finish()
    }
}

#[cfg(test)]
mod typed_subscription_tests {
    use super::*;

    #[derive(Debug)]
    struct Row;

    impl FromBatch for Row {
        fn from_batch(_batch: &RecordBatch, _row: usize) -> Self {
            Self
        }

        fn from_batch_all(_batch: &RecordBatch) -> Vec<Self> {
            Vec::new()
        }
    }

    #[test]
    fn delivery_gap_is_not_converted_to_empty_poll() {
        let error =
            convert_typed_frame::<Row>(crate::subscription::PortalFrame::Lagged(7)).unwrap_err();
        assert_eq!(error, SubscriptionError::Lagged { skipped: 7 });
    }

    #[test]
    fn delivery_failure_preserves_detail() {
        let error = convert_typed_frame::<Row>(crate::subscription::PortalFrame::Error {
            message: "object dropped".into(),
        })
        .unwrap_err();
        assert_eq!(
            error,
            SubscriptionError::Failed {
                message: "object dropped".into()
            }
        );
    }
}

/// Typed handle for pushing data into a registered source.
pub struct SourceHandle<T: Record> {
    entry: Arc<SourceEntry>,
    _phantom: PhantomData<T>,
}

impl<T: Record> SourceHandle<T> {
    /// Validates that `T`'s schema matches the source schema.
    pub(crate) fn new(entry: Arc<SourceEntry>) -> Result<Self, DbError> {
        let rust_schema = T::schema();
        let sql_schema = &entry.schema;

        // Validate field count matches
        if rust_schema.fields().len() != sql_schema.fields().len() {
            return Err(DbError::SchemaMismatch(format!(
                "Rust type has {} fields but source '{}' has {} columns",
                rust_schema.fields().len(),
                entry.name,
                sql_schema.fields().len()
            )));
        }

        Ok(Self {
            entry,
            _phantom: PhantomData,
        })
    }

    /// Push a single record.
    ///
    /// # Errors
    /// Returns `StreamingError` if the pipeline is not running.
    #[allow(clippy::needless_pass_by_value)]
    pub fn push(&self, record: T) -> Result<(), laminar_core::streaming::StreamingError> {
        let batch = record.to_record_batch();
        self.entry.push_and_buffer(batch)
    }

    /// Push multiple records, returns count successfully sent.
    pub fn push_batch(&self, records: impl IntoIterator<Item = T>) -> usize {
        const BATCH_SIZE: usize = 1024;
        let mut count = 0;
        let mut buffer = Vec::with_capacity(BATCH_SIZE);

        for record in records {
            buffer.push(record);
            if buffer.len() >= BATCH_SIZE {
                let batch = T::to_record_batch_from_iter(buffer.drain(..));
                if self.push_arrow(batch).is_err() {
                    return count;
                }
                count += BATCH_SIZE;
            }
        }

        if !buffer.is_empty() {
            let len = buffer.len();
            let batch = T::to_record_batch_from_iter(buffer);
            if self.push_arrow(batch).is_ok() {
                count += len;
            }
        }
        count
    }

    /// Push a raw `RecordBatch` (sent to pipeline and buffered for snapshots).
    ///
    /// # Errors
    /// Returns `StreamingError` if the pipeline is not running.
    pub fn push_arrow(
        &self,
        batch: RecordBatch,
    ) -> Result<(), laminar_core::streaming::StreamingError> {
        self.entry.push_and_buffer(batch)
    }

    /// Emit a watermark.
    pub fn watermark(&self, timestamp: i64) {
        self.entry.source.watermark(timestamp);
    }

    /// Current watermark.
    #[must_use]
    pub fn current_watermark(&self) -> i64 {
        self.entry.source.current_watermark()
    }

    /// Buffered record count.
    #[must_use]
    pub fn pending(&self) -> usize {
        self.entry.source.pending()
    }

    /// Buffer capacity.
    #[must_use]
    pub fn capacity(&self) -> usize {
        self.entry.source.capacity()
    }

    /// True when buffer is >80% full.
    #[must_use]
    pub fn is_backpressured(&self) -> bool {
        crate::metrics::is_backpressured(self.pending(), self.capacity())
    }

    /// Source name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.entry.name
    }

    /// Schema.
    #[must_use]
    pub fn schema(&self) -> &SchemaRef {
        &self.entry.schema
    }

    /// Max out-of-orderness, if configured.
    #[must_use]
    pub fn max_out_of_orderness(&self) -> Option<Duration> {
        self.entry.max_out_of_orderness
    }

    /// Set the event-time column for watermark-based late-row filtering.
    pub fn set_event_time_column(&self, column: &str) {
        self.entry.source.set_event_time_column(column);
    }
}

impl<T: Record> std::fmt::Debug for SourceHandle<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SourceHandle")
            .field("name", &self.entry.name)
            .field("pending", &self.pending())
            .finish()
    }
}

/// Untyped handle for pushing raw `RecordBatch` data.
pub struct UntypedSourceHandle {
    entry: Arc<SourceEntry>,
}

impl UntypedSourceHandle {
    pub(crate) fn new(entry: Arc<SourceEntry>) -> Self {
        Self { entry }
    }

    /// Push a raw `RecordBatch` (sent to pipeline and buffered for snapshots).
    ///
    /// # Errors
    /// Returns `StreamingError` if the pipeline is not running.
    pub fn push_arrow(
        &self,
        batch: RecordBatch,
    ) -> Result<(), laminar_core::streaming::StreamingError> {
        self.entry.push_and_buffer(batch)
    }

    /// Emit a watermark.
    pub fn watermark(&self, timestamp: i64) {
        self.entry.source.watermark(timestamp);
    }

    /// Current watermark.
    #[must_use]
    pub fn current_watermark(&self) -> i64 {
        self.entry.source.current_watermark()
    }

    /// Buffered record count.
    #[must_use]
    pub fn pending(&self) -> usize {
        self.entry.source.pending()
    }

    /// Buffer capacity.
    #[must_use]
    pub fn capacity(&self) -> usize {
        self.entry.source.capacity()
    }

    /// True when buffer is >80% full.
    #[must_use]
    pub fn is_backpressured(&self) -> bool {
        crate::metrics::is_backpressured(self.pending(), self.capacity())
    }

    /// Source name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.entry.name
    }

    /// Schema.
    #[must_use]
    pub fn schema(&self) -> &SchemaRef {
        &self.entry.schema
    }

    /// Max out-of-orderness, if configured.
    #[must_use]
    pub fn max_out_of_orderness(&self) -> Option<Duration> {
        self.entry.max_out_of_orderness
    }

    /// Set the event-time column for watermark-based late-row filtering.
    pub fn set_event_time_column(&self, column: &str) {
        self.entry.source.set_event_time_column(column);
    }
}

impl std::fmt::Debug for UntypedSourceHandle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UntypedSourceHandle")
            .field("name", &self.entry.name)
            .finish()
    }
}

/// Type of a node in the pipeline topology.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PipelineNodeType {
    /// A data source (CREATE SOURCE).
    Source,
    /// A continuous stream (CREATE STREAM).
    Stream,
    /// A data sink (CREATE SINK).
    Sink,
}

/// A node in the pipeline topology graph.
#[derive(Debug, Clone)]
pub struct PipelineNode {
    /// Node name.
    pub name: String,
    /// Node type.
    pub node_type: PipelineNodeType,
    /// Arrow schema (sources only).
    pub schema: Option<SchemaRef>,
    /// SQL definition (streams only).
    pub sql: Option<String>,
}

/// A directed edge in the pipeline topology graph.
#[derive(Debug, Clone)]
pub struct PipelineEdge {
    /// Source node.
    pub from: String,
    /// Target node.
    pub to: String,
}

/// The complete pipeline topology: nodes and edges.
#[derive(Debug, Clone)]
pub struct PipelineTopology {
    /// Nodes.
    pub nodes: Vec<PipelineNode>,
    /// Edges.
    pub edges: Vec<PipelineEdge>,
}

/// Metadata about a registered stream.
#[derive(Debug, Clone)]
pub struct StreamInfo {
    /// Name.
    pub name: String,
    /// Defining SQL query.
    pub sql: Option<String>,
}

/// Information about a registered source.
#[derive(Debug, Clone)]
pub struct SourceInfo {
    /// Name.
    pub name: String,
    /// Schema.
    pub schema: SchemaRef,
    /// Watermark column, if configured.
    pub watermark_column: Option<String>,
}

/// Information about a registered sink.
#[derive(Debug, Clone)]
pub struct SinkInfo {
    /// Name.
    pub name: String,
}

/// JSON-serializable projection of a `MaterializedView` for the control-plane
/// HTTP API.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MaterializedViewInfo {
    /// View name.
    pub name: String,
    /// SQL definition.
    pub sql: String,
    /// Current execution state (e.g. `"Running"`, `"Dropping"`).
    pub state: String,
}

impl From<&laminar_core::mv::MaterializedView> for MaterializedViewInfo {
    fn from(view: &laminar_core::mv::MaterializedView) -> Self {
        Self {
            name: view.name.clone(),
            sql: view.sql.clone(),
            state: format!("{:?}", view.state),
        }
    }
}

/// Information about a running query.
#[derive(Debug, Clone)]
pub struct QueryInfo {
    /// ID.
    pub id: u64,
    /// SQL text.
    pub sql: String,
    /// Active.
    pub active: bool,
}
